# Generated by Django 5.2.4 on 2025-07-05 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='is_paid',
            new_name='paid',
        ),
    ]
