# Generated by Django 5.2.4 on 2025-07-06 17:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0003_rename_is_paid_reservation_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='tickets',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1, message='Number of tickets must be greater than zero')]),
        ),
    ]
